services:
  mongo:
    container_name: mongo
    image: mongo:8.2
    ports:
      - "27017:27017"
    tmpfs:
      - /data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
